// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZGwGILd_XWdWK6Gd5kFsBX3AcK08-c4I',
    appId: '1:345217019740:web:79fa3b75ea8e0dab1ddb99',
    messagingSenderId: '345217019740',
    projectId: 'coolmate-578b6',
    authDomain: 'coolmate-578b6.firebaseapp.com',
    databaseURL: 'https://coolmate-578b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coolmate-578b6.appspot.com',
    measurementId: 'G-8Z9K750L4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA4igZbxle-Z-Z87F4e6ZqMFGqE6AiYX4',
    appId: '1:345217019740:android:071c45a809e57af21ddb99',
    messagingSenderId: '345217019740',
    projectId: 'coolmate-578b6',
    databaseURL: 'https://coolmate-578b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coolmate-578b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqeuBXlU5D0tU3b6ArIjH4-O4o2WhijuA',
    appId: '1:345217019740:ios:ad257daf171972d61ddb99',
    messagingSenderId: '345217019740',
    projectId: 'coolmate-578b6',
    databaseURL: 'https://coolmate-578b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coolmate-578b6.appspot.com',
    iosClientId: '345217019740-v7ikplre0n1ble821fdid0b3lftals9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.coolmate',
  );
}
